### ISSUE TITLE
ERROR: Couldn't insert module '/tmp/stapsGgSVk/uprobes/uprobes.ko': Unknown symbol in module

### ISSUE THREAD

**Issue by CCMBChina** [openresty/openresty-systemtap-toolkit#38]
when i first use this toolkit，console shows :+1: 
ERROR: Couldn't insert module '/tmp/stapsGgSVk/uprobes/uprobes.ko': Unknown symbol in module
WARNING: /opt/stap/bin/staprun exited with status: 1
Pass 5: run failed.  [man error::pass5]

my linux kernel is 2.6.32-358.el6.x86_64 redhat

**Comment by agentzh** [comment]
Seems like your default gcc is not the same C compiler that is used to compile your kernel binary. BTW, such general systemtap questions should ask on the systemtap mailing list instead. We do not support that. This is obviously your systemtap installation or setup problems.
