### ISSUE TITLE
semantic error: while resolving probe point: identifier 'scheduler' at

### ISSUE THREAD

**Issue by devil0118** [openresty/openresty-systemtap-toolkit#39]
![image](https://cloud.githubusercontent.com/assets/4556669/26384970/3cab7b90-406f-11e7-8a95-a5ed1b775c16.png)

请问这是怎么回事呢？
yum install kernel-devel yum-utils 
debuginfo-install kernel 
都已经安装

**Comment by agentzh** [comment]
Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.
