### ISSUE TITLE
how to fix ./ngx_shm error???

### ISSUE THREAD

**Issue by Zeecoders** [openresty/openresty-systemtap-toolkit#41]
In file included from /usr/share/systemtap/runtime/linux/runtime.h:204:0,
                 from /usr/share/systemtap/runtime/runtime.h:24,
                 from /tmp/stapxGvprS/stap_31cf294d07d22dfccb628e8b8cff9a02_16701_src.c:25:
/usr/share/systemtap/runtime/linux/access_process_vm.h: In function '__access_process_vm_':
/usr/share/systemtap/runtime/linux/access_process_vm.h:35:29: error: passing argument 1 of 'get_user_pages' makes integer from pointer without a cast [-Werror=int-conversion]
       ret = get_user_pages (tsk, mm, addr, 1, write, 1, &page, &vma);
                             ^
In file included from ./include/linux/pid_namespace.h:6:0,
                 from ./include/linux/ptrace.h:8,
                 from ./include/linux/ftrace.h:13,
                 from ./include/linux/kprobes.h:42,
                 from /usr/share/systemtap/runtime/linux/runtime.h:21,
                 from /usr/share/systemtap/runtime/runtime.h:24,
                 from /tmp/stapxGvprS/stap_31cf294d07d22dfccb628e8b8cff9a02_16701_src.c:25:
./include/linux/mm.h:1293:6: note: expected 'long unsigned int' but argument is of type 'struct task_struct *'
 long get_user_pages(unsigned long start, unsigned long nr_pages,
      ^
In file included from /usr/share/systemtap/runtime/linux/runtime.h:204:0,
                 from /usr/share/systemtap/runtime/runtime.h:24,
                 from /tmp/stapxGvprS/stap_31cf294d07d22dfccb628e8b8cff9a02_16701_src.c:25:
/usr/share/systemtap/runtime/linux/access_process_vm.h:35:34: error: passing argument 2 of 'get_user_pages' makes integer from pointer without a cast [-Werror=int-conversion]
       ret = get_user_pages (tsk, mm, addr, 1, write, 1, &page, &vma);
                                  ^
In file included from ./include/linux/pid_namespace.h:6:0,
                 from ./include/linux/ptrace.h:8,
                 from ./include/linux/ftrace.h:13,
                 from ./include/linux/kprobes.h:42,
                 from /usr/share/systemtap/runtime/linux/runtime.h:21,
                 from /usr/share/systemtap/runtime/runtime.h:24,
                 from /tmp/stapxGvprS/stap_31cf294d07d22dfccb628e8b8cff9a02_16701_src.c:25:
./include/linux/mm.h:1293:6: note: expected 'long unsigned int' but argument is of type 'struct mm_struct *'
 long get_user_pages(unsigned long start, unsigned long nr_pages,
      ^
In file included from /usr/share/systemtap/runtime/linux/runtime.h:204:0,
                 from /usr/share/systemtap/runtime/runtime.h:24,
                 from /tmp/stapxGvprS/stap_31cf294d07d22dfccb628e8b8cff9a02_16701_src.c:25:
/usr/share/systemtap/runtime/linux/access_process_vm.h:35:44: error: passing argument 4 of 'get_user_pages' makes pointer from integer without a cast [-Werror=int-conversion]
       ret = get_user_pages (tsk, mm, addr, 1, write, 1, &page, &vma);
                                            ^
In file included from ./include/linux/pid_namespace.h:6:0,
                 from ./include/linux/ptrace.h:8,
                 from ./include/linux/ftrace.h:13,
                 from ./include/linux/kprobes.h:42,
                 from /usr/share/systemtap/runtime/linux/runtime.h:21,
                 from /usr/share/systemtap/runtime/runtime.h:24,
                 from /tmp/stapxGvprS/stap_31cf294d07d22dfccb628e8b8cff9a02_16701_src.c:25:
./include/linux/mm.h:1293:6: note: expected 'struct page **' but argument is of type 'int'
 long get_user_pages(unsigned long start, unsigned long nr_pages,
      ^
In file included from /usr/share/systemtap/runtime/linux/runtime.h:204:0,
                 from /usr/share/systemtap/runtime/runtime.h:24,
                 from /tmp/stapxGvprS/stap_31cf294d07d22dfccb628e8b8cff9a02_16701_src.c:25:
/usr/share/systemtap/runtime/linux/access_process_vm.h:35:47: error: passing argument 5 of 'get_user_pages' makes pointer from integer without a cast [-Werror=int-conversion]
       ret = get_user_pages (tsk, mm, addr, 1, write, 1, &page, &vma);
                                               ^
In file included from ./include/linux/pid_namespace.h:6:0,
                 from ./include/linux/ptrace.h:8,
                 from ./include/linux/ftrace.h:13,
                 from ./include/linux/kprobes.h:42,
                 from /usr/share/systemtap/runtime/linux/runtime.h:21,
                 from /usr/share/systemtap/runtime/runtime.h:24,
                 from /tmp/stapxGvprS/stap_31cf294d07d22dfccb628e8b8cff9a02_16701_src.c:25:
./include/linux/mm.h:1293:6: note: expected 'struct vm_area_struct **' but argument is of type 'int'
 long get_user_pages(unsigned long start, unsigned long nr_pages,
      ^
In file included from /usr/share/systemtap/runtime/linux/runtime.h:204:0,
                 from /usr/share/systemtap/runtime/runtime.h:24,
                 from /tmp/stapxGvprS/stap_31cf294d07d22dfccb628e8b8cff9a02_16701_src.c:25:
/usr/share/systemtap/runtime/linux/access_process_vm.h:35:13: error: too many arguments to function 'get_user_pages'
       ret = get_user_pages (tsk, mm, addr, 1, write, 1, &page, &vma);
             ^
In file included from ./include/linux/pid_namespace.h:6:0,
                 from ./include/linux/ptrace.h:8,
                 from ./include/linux/ftrace.h:13,
                 from ./include/linux/kprobes.h:42,
                 from /usr/share/systemtap/runtime/linux/runtime.h:21,
                 from /usr/share/systemtap/runtime/runtime.h:24,
                 from /tmp/stapxGvprS/stap_31cf294d07d22dfccb628e8b8cff9a02_16701_src.c:25:
./include/linux/mm.h:1293:6: note: declared here
 long get_user_pages(unsigned long start, unsigned long nr_pages,
      ^
In file included from /usr/share/systemtap/runtime/linux/runtime.h:204:0,
                 from /usr/share/systemtap/runtime/runtime.h:24,
                 from /tmp/stapxGvprS/stap_31cf294d07d22dfccb628e8b8cff9a02_16701_src.c:25:
/usr/share/systemtap/runtime/linux/access_process_vm.h:55:7: error: implicit declaration of function 'page_cache_release' [-Werror=implicit-function-declaration]
       page_cache_release (page);
       ^
In file included from /usr/share/systemtap/runtime/linux/print.c:17:0,
                 from /usr/share/systemtap/runtime/print.c:17,
                 from /usr/share/systemtap/runtime/runtime_context.h:22,
                 from /tmp/stapxGvprS/stap_31cf294d07d22dfccb628e8b8cff9a02_16701_src.c:376:
/usr/share/systemtap/runtime/transport/transport.c: In function '_stp_lock_inode':
/usr/share/systemtap/runtime/transport/transport.c:506:19: error: 'struct inode' has no member named 'i_mutex'
  mutex_lock(&inode->i_mutex);
                   ^
/usr/share/systemtap/runtime/transport/transport.c: In function '_stp_unlock_inode':
/usr/share/systemtap/runtime/transport/transport.c:515:21: error: 'struct inode' has no member named 'i_mutex'
  mutex_unlock(&inode->i_mutex);
                     ^

**Comment by agentzh** [comment]
@Zeecoders Looks like your systemtap is (a lot) older than your linux kernels. You should try the latest systemtap source release:

https://sourceware.org/systemtap/ftp/releases/

**Comment by Zeecoders** [comment]
/home/elfutils-0.148/lib/md5.c: In function ‘md5_finish_ctx’:
/home/elfutils-0.148/lib/md5.c:108:3: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   *(md5_uint32 *) &ctx->buffer[bytes + pad] = SWAP (ctx->total[0] << 3);
   ^
/home/elfutils-0.148/lib/md5.c:109:3: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   *(md5_uint32 *) &ctx->buffer[bytes + pad + 4] = SWAP ((ctx->total[1] << 3) |
   ^

**Comment by agentzh** [comment]
@Zeecoders You should remove `-Werror` from the C compiler options when building this library. BTW, you should really report this to the elfutils project instead. That's already far beyond the scope of this repo anyway :)

**Comment by Zeecoders** [comment]
➜  Documents sudo ./ngx_shm -p 5477
semantic error: libdwfl failure (dwarf_highpc): no error

semantic error: while resolving probe point: identifier 'process' at <input>:5:7
        source: probe process("/home/zhangcheng/Documents/nginx-http-dns/build/sbin/nginx").function("ngx_process_events_and_timers"),
                      ^

semantic error: no match (similar functions: ngx_process_events_and_timers, ngx_event_add_timer, ngx_event_find_timer, ngx_event_cancel_timers, ngx_event_del_timer)

Pass 2: analysis failed.  [man error::pass2]
Number of similar error messages suppressed: 2.
Rerun with -v to see them.
