### ISSUE TITLE
ngx-shm sometimes faults when checking a worker process

### ISSUE THREAD

**Issue by davidsiracusa** [openresty/openresty-systemtap-toolkit#43]
OpenResty version: ngx_openresty-1.7.10.1
OS: Linux ip-10-0-2-4 3.13.0-133-generic #182-Ubuntu SMP Tue Sep 19 15:49:21 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Test Case
1.Using Kong 0.11.0

I noticed that ngx-shm sometimes faults when checking a worker.
 bash-4.1$ ./ngx-shm -p 28577 -n kong_cache
 Tracing 28577 (/usr/local/openresty/nginx/sbin/nginx)...

shm zone "kong_cache"
 owner: ngx_http_lua_shared_memory
 total size: 1048576 KB
 free pages: 1029488 KB (257372 pages, 1 blocks)

10 microseconds elapsed in the probe handler.
 bash-4.1$
 bash-4.1$ ./ngx-shm -p 28576 -n kong_cache
 Tracing 28576 (/usr/local/openresty/nginx/sbin/nginx)...

shm zone "kong_cache"
 owner: ngx_http_lua_shared_memory
 total size: 1048576 KB
 free pages: 1029488 KB (257372 pages, 1 blocks)

11 microseconds elapsed in the probe handler.
 bash-4.1$
 bash-4.1$ ./ngx-shm -p 28578 -n kong_cache
 Tracing 28578 (/usr/local/openresty/nginx/sbin/nginx)...

shm zone "kong_cache"
 owner: ngx_http_lua_shared_memory
 total size: 1048576 KB
 free pages: 1029488 KB (257372 pages, 1 blocks)

11 microseconds elapsed in the probe handler.
 bash-4.1$
 bash-4.1$ ./ngx-shm -p 28580 -n kong_cache
**ERROR: read fault [man error::fault] at 0x00007f1f543b31b0 (addr) near operator '@cast' at :76:26
 Tracing 28580 (/usr/local/openresty/nginx/sbin/nginx)...

shm zone "kong_cache"
 owner: ngx_http_lua_shared_memory
 total size: 1048576 KB
WARNING: Number of errors: 1, skipped probes: 0
 WARNING: /usr/bin/staprun exited with status: 1
 Pass 5: run failed. [man error::pass5]**
 bash-4.1$ ./ngx-shm -p 28579 -n kong_cache
 Tracing 28579 (/usr/local/openresty/nginx/sbin/nginx)...

shm zone "kong_cache"
 owner: ngx_http_lua_shared_memory
 total size: 1048576 KB
 free pages: 1029488 KB (257372 pages, 1 blocks)

11 microseconds elapsed in the probe handler.

**Comment by agentzh** [comment]
@davidsiracusa Page faults are completely normal for shm zones due to modern operating systems' on-demand paging optimizations, basically an already mapped memory page would not actually load into a process's process space until the process actually uses it (systemtap tools do not count since they are pure observers). And a page fault handler is the code doing on-demand memory loading.
