### ISSUE TITLE
semantic error: while resolving probe point: identifier 'scheduler' at <input>:29:7

### ISSUE THREAD

**Issue by achilsh** [openresty/openresty-systemtap-toolkit#44]
semantic error: while resolving probe point: identifier 'scheduler' at <input>:29:7
        source: probe scheduler.cpu_on {
                      ^

semantic error: no match

Pass 2: analysis failed.  [man error::pass2]
ERROR: No stack counts found

**Comment by achilsh** [comment]
use sample-bt-off-cpu  file to get off-cpu

**Comment by agentzh** [comment]
@achilsh Seems like you forgot to install the kernel debuginfo package?

**Comment by WiFeng** [comment]
I had the same problem.

**Comment by agentzh** [comment]
@danialgood Yeah, it's recommended to always use the latest upstream version of systemtap.
